# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on: [ push, pull_request ]

jobs:
    build:
        strategy:
            matrix:
                node-version: [20.x, 21.x]
                os: [ubuntu-latest]
       
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: "Install Dependencies (Frontend)"
              run: cd frontend && npm install

            - name: "Install Dev Dependencies (Frontend)"
              run: cd frontend && npm install -D

            - name: "Build (Frontend)"
              run: cd frontend && npm run build

            - name: "Install Dependencies (Backend)"
              run: cd backend && npm install

            - name: "Install Dev Dependencies (Backend)"
              run: cd backend && npm install -D

            - name: "Build (Backend)"
              run: cd backend && npm run build
